DELETE FROM SALE WHERE PRODUCT_ID = 1;
DELETE FROM PRODUCT WHERE ID=1;

INSERT INTO PRODUCT (ID, NAME, IN_STOCK, CREATION_DATE) VALUES  (1, 'PRODUCT_1', true, TO_TIMESTAMP('2022-03-14-00.00.00','YYYY-MM-DD-HH24.MI.SS'));

INSERT INTO SALE (PRODUCT_ID, USER_ID, AMOUNT) VALUES (1, 2, 5);
INSERT INTO SALE (PRODUCT_ID, USER_ID, AMOUNT) VALUES (1, 65, 1);
