DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS SALE;

CREATE TABLE PRODUCT (
  ID NUMBER AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  IN_STOCK BOOLEAN DEFAULT FALSE,
  CREATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSDATE,
  ATTRIBUTES VARCHAR(200) DEFAULT 'EUR'
);

CREATE TABLE BRAND (
  ID NUMBER AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  CREATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSDATE
);

CREATE TABLE PRICES (
  ID NUMBER AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID NUMBER NOT NULL,
  BRAND_ID NUMBER NOT NULL,
  START_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSDATE,
  END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
  PRICE_LIST NUMBER(1) NOT NULL,
  PRIORITY NUMBER(1),
  PRICE NUMBER(10,2) NOT NULL,
  CURR VARCHAR(3) DEFAULT 'EUR',
  CONSTRAINT FK_PRICES_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_PRICES_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE SALE  (
  PRODUCT_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  AMOUNT NUMBER(5) NOT NULL,
  PRIMARY KEY (PRODUCT_ID, USER_ID),
  CONSTRAINT FK_SALE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

INSERT INTO PRODUCT (ID, NAME, IN_STOCK) VALUES
  (35455, 'PRODUCT_35455', true);

INSERT INTO BRAND (ID, NAME) VALUES (1, 'BRAND_1');

INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR) VALUES
  (1, TO_TIMESTAMP('2020-06-14-00.00.00','YYYY-MM-DD-HH24.MI.SS'), TO_TIMESTAMP('2020-12-31-23.59.59','YYYY-MM-DD-HH24.MI.SS'), 1, 35455, 0, 35.50, 'EUR'),
  (1, TO_TIMESTAMP('2020-06-14-15.00.00','YYYY-MM-DD-HH24.MI.SS'), TO_TIMESTAMP('2020-06-14-18.30.00','YYYY-MM-DD-HH24.MI.SS'), 2, 35455, 1, 25.45, 'EUR'),
  (1, TO_TIMESTAMP('2020-06-15-00.00.00','YYYY-MM-DD-HH24.MI.SS'), TO_TIMESTAMP('2020-06-15-11.00.00','YYYY-MM-DD-HH24.MI.SS'), 3, 35455, 1, 30.50, 'EUR'),
  (1, TO_TIMESTAMP('2020-06-15-16.00.00','YYYY-MM-DD-HH24.MI.SS'), TO_TIMESTAMP('2020-12-31-23.59.59','YYYY-MM-DD-HH24.MI.SS'), 4, 35455, 1, 38.95, 'EUR');

INSERT INTO SALE (PRODUCT_ID, USER_ID, AMOUNT) VALUES (35455, 1, 2);
